name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        config:
        - { os: ubuntu-24.04, add_inc: '' }
        - { os: macos-latest, add_inc: '/opt/homebrew/include' }
        - { os: windows-latest, add_inc: '' }
    runs-on: ${{ matrix.config.os }}

    env:
      CMAKE_PREFIX_PATH: ${{ github.workspace }}/pon
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Developer Command Prompt
      if: ${{ startsWith( matrix.config.os , 'windows') }}
      uses: ilammy/msvc-dev-cmd@v1

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install toml++
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/marzer/tomlplusplus.git -b v3.4.0 --depth 1
        cd tomlplusplus
        cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        cmake --install build --config Release --prefix=${{ github.workspace }}/pon

    - name: Install SDL2
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/libsdl-org/SDL.git -b release-2.30.8 --depth 1 --recursive
        cd SDL
        cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        cmake --install build --config Release --prefix=${{ github.workspace }}/pon

    - name: Install SDL2_mixer
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/libsdl-org/SDL_mixer.git -b SDL2 --depth 1 --recursive
        cd SDL_mixer
        cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=Release -DSDL2MIXER_VENDORED=ON
        cmake --build build --config Release
        cmake --install build --config Release --prefix=${{ github.workspace }}/pon

    - name: Build
      run: |
        cd ${{ github.workspace }}
        cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=Release -DADD_INCLUDE_DIR=${{ matrix.config.add_inc }}
        cmake --build build --config Release
    
    - name: patch (macOS arm64)
      run: |
        cd ${{ github.workspace }}/build/bin
        install_name_tool -add_rpath /opt/homebrew/lib Pon

    - name: Create Archive
      shell: pwsh
      run: |
        cd ${{ github.workspace }}/build/bin
        7z a Pon_${{ matrix.config.os }}.zip *
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pon-${{ matrix.config.os }}
        path: ${{ github.workspace }}/build/bin/Pon_${{ matrix.config.os }}.zip
        