name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        config:
        - { os: ubuntu-latest, add_inc: ''}
        - { os: macos-latest, add_inc: '/opt/homebrew/include' }
    runs-on: ${{ matrix.config.os }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name:  Setup depends (Ubuntu)
      if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build

    - name: Setup depends (macOS)
      if: ${{ startsWith(matrix.config.os, 'macos') }}
      run: |
        brew install ninja

    - name: Install toml++
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/marzer/tomlplusplus.git -b v3.4.0 --depth 1
        cd tomlplusplus
        cmake -B build . -G Ninja
        sudo cmake --install build

    - name: Install SDL2
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/libsdl-org/SDL.git -b 2.30.8 --depth 1
        cd SDL
        cmake -B build . -G Ninja
        sudo cmake --install build

    - name: Install SDL2_mixer
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/libsdl-org/SDL_mixer.git -b 2.8.0 --depth 1
        cd SDL_mixer
        cmake -B build . -G Ninja
        sudo cmake --install build

    - name: Build
      run: |
        cd ${{ github.workspace }}
        cmake -B build . -G Ninja -DADD_INCLUDE_DIR=${{ matrix.config.add_inc }}
        cmake --build build --config Release

    - name: Create Archive
      shell: pwsh
      run: |
        cd ${{ github.workspace }}/build
        mkdir pub
        cp Pon* pub
        cd pub
        7z a Pon_${{ matrix.config.os }}.zip *
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pon-${{ matrix.config.os }}
        path: ${{ github.workspace }}/build/pub/Pon_${{ matrix.config.os }}.zip
        