name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        config:
        - { os: ubuntu-latest, add_inc: ''}
        - { os: macos-latest, add_inc: '/opt/homebrew/include' }
    runs-on: ${{ matrix.config.os }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name:  Setup depends (Ubuntu)
      if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build libsdl2-dev libsdl2-mixer-dev

    - name: Setup depends (macOS)
      if: ${{ startsWith(matrix.config.os, 'macos') }}
      run: |
        brew install ninja tomlplusplus sdl2 sdl2_mixer

    - name: Build
      run: |
        cd ${{ github.workspace }}
        cmake -B build . -G Ninja -DADD_INCLUDE_DIR=${{ matrix.config.add_inc }}
        cmake --build build --config Release

    - name: Create Archive
      shell: pwsh
      run: |
        cd ${{ github.workspace }}/build
        mkdir pub
        cp Pon* pub
        cd pub
        7z a Pon_${{ matrix.config.os }}.zip *
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pon-${{ matrix.config.os }}
        path: ${{ github.workspace }}/build/pub/Pon_${{ matrix.config.os }}.zip
        